#!/bin/sh
### BEGIN INIT INFO
# Authors: fuzhouch@microsoft.com
# Provides: icadaemon
# Required-Start: $syslog
# Required-Stop:  $syslog
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description: ICADaemon management script
### END INIT INFO
#
### BEGIN FREEBSD INFO
# PROVIDE: icadaemon
# REQUIRE: syslogd
### END FREEBSD INFO
#
# This is the management script that should be put under /etc/init.d/
# directory to control the start or stop of icadaemon. This script is
# compatible with SysV style system, mostly RedHat and SUSE family
# systems.
#

export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
PIDFILE=/var/run/icadaemon.pid
PROG="ICADaemon"

RESULT_FAIL="FAIL"
RESULT_OK="OK"
EXITCODE=0

print_result() {
    if [ "$1" = "$RESULT_OK" ]; then
        echo "[  OK  ]"
    fi
    if [ "$1" = "$RESULT_FAIL" ]; then
        echo "[ FAIL ]"
    fi
}

start() {
    echo -n "Starting $PROG: "
    /usr/bin/env icadaemon > /dev/null 2>&1
    EXITCODE=$?
    if [ "$EXITCODE" = "0" ]; then
        RESULT=$RESULT_OK
    else
        RESULT=$RESULT_FAIL
    fi
    print_result $RESULT
}

stop() {
    echo -n "Stopping $PROG: "
    EXITCODE=0
    if [ -e "$PIDFILE" ]; then
        PID=`cat $PIDFILE`
        if [ "$PID" = "" ]; then
            RESULT=$RESULT_FAIL
        else
            kill $PID
            EXITCODE=$?
            if [ "$EXITCODE" = "0" ]; then
                RESULT=$RESULT_OK
            else
                RESULT=$RESULT_FAIL
            fi
        fi
    else
        RESULT=$RESULT_OK
    fi
    print_result $RESULT
}
restart() {
    stop
    start
}
reload() {
    restart
}
force_reload() {
    stop
    rm -f /var/run/icadaemon* > /dev/null 2>&1
    start
}
status() {
    if [ -e "$PIDFILE" ]; then
        echo "Running"
    else
        echo "Stopped"
    fi
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        $1
        ;;
    force-reload)
        $1
        ;;
    status)
        $1
        ;;
    *)
        echo "Usage $0 {start|stop|status|restart|force-reload|reload"
        exit 1
esac
exit $EXITCODE
#vim:ff=unix
